title: JueJin Book
subtitle: Endless learning, progress together!
language: en
timezone: Asia/Shanghai

url: https://Flashcard8009.github.io/book
permalink: :title/

archive_generator:
  per_page: 25

theme: maupassant

public_dir: ../public/en
