title: 掘金小册
subtitle: 学海无涯，共同进步！
language: zh-CN
timezone: Asia/Shanghai

url: https://Flashcard8009.github.io/book
permalink: :title/

archive_generator:
  per_page: 25

theme: maupassant

public_dir: ../public
